server:
  port: 9000
  
  
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: orderservice
        uri: http://localhost:8082/
        predicates:
        - Path=/allorders/**
        
        
        
        
        
        
