server:
  port: 9000
  
  
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: orderservice
        uri: http://localhost:8083/
        predicates:
        - Path=/orders/**
        
     
      - id: admin service
        uri: http://localhost:8091/
        predicates:
        - Path=/admins/**
        
        #Route Mapping

       


        


        
        
        
        
        
        
